### ISSUE TITLE
Configuring vyper.command for project's venv

### ISSUE THREAD

**Issue by nicklatkovich** [tintinweb/vscode-vyper#3]
> It is assumed that vyper is installed and generally available on the system (pip install vyper). In case vyper is not available in path or called in a virtualenv configure the vyper command in Settings → Vyper → Command

Can not make to extension to watch venv directory to get vyper compiler. The only one way, that works, is:
```
/home/username/path-to-project/venv/bin/vyper
```
But relative paths not working:
```
venv/bin/vyper
./venv/bin/vyper
${workspaceRoot}/venv/bin/vyper
${workspaceFolder}/venv/bin/vyper
```

**Comment by tintinweb** [comment]
just pushed a change tracked in #5 that allows you to specify workspace relative vyper commands.

e.g.

in case you always have a virtual-env `.py3env` in your workspace folder with vyper installed in it you can configure this as you command:

`. .py3env/bin/activate && python -m vyper`

otherwise I'd suggest to make vyper generally available on the system or use a wrapper script in a static location that invokes vyper.
